/* Copyright (C) YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(e){function m(a){return $widgetkit.css3(a)}var r=$widgetkit.support,i=function(){};i.prototype=e.extend(i.prototype,{name:"slideshow",options:{index:0,width:"auto",height:"auto",autoplay:true,interval:5E3,navbar_items:4,caption_animation_duration:500,kenburns_animation_duration:null,slices:20,duration:500,animated:"random",easing:"swing"},nav:null,navbar:null,captions:null,caption:null,kbi:0,initialize:function(a,c){var b=this;this.options=e.extend({},this.options,c);this.element=this.wrapper=
a;this.ul=this.wrapper.find("ul.slides:first").css({width:"100%",overflow:"hidden"});this.wrapper.css({position:"relative"});this.slides=this.ul.css({position:"relative"}).children().css({top:"0px",left:"0px",position:"absolute"}).hide();this.index=this.slides[this.options.index]?this.options.index:0;e(".next",this.wrapper).bind("click",function(){b.stop();b.nextSlide()});e(".prev",this.wrapper).bind("click",function(){b.stop();b.prevSlide()});if(this.wrapper.find(".nav:first").length){this.nav=this.wrapper.find(".nav:first");
var d=this.nav.children();d.each(function(a){e(this).bind("click",function(){b.stop();b.slides[a]&&b.show(a)})});a.bind("slideshow-show",function(a,b,c){e(d.removeClass("active").get(c)).addClass("active")})}if(this.wrapper.find(".captions:first").length&&this.wrapper.find(".caption:first").length)this.captions=this.wrapper.find(".captions:first").hide().children(),this.caption=this.wrapper.find(".caption:first").hide();this.nav&&e(this.nav.children().get(this.index)).addClass("active");this.navbar&&
e(this.navbar.children().get(this.index)).addClass("active");this.showCaption(this.index);this.timer=null;this.hover=false;this.wrapper.hover(function(){b.hover=true},function(){b.hover=false});"ontouchend"in document&&(a.bind("touchstart",function(b){function c(a){if(g){var b=a.originalEvent.touches?a.originalEvent.touches[0]:a;l={time:(new Date).getTime(),coords:[b.pageX,b.pageY]};Math.abs(g.coords[0]-l.coords[0])>10&&a.preventDefault()}}var d=b.originalEvent.touches?b.originalEvent.touches[0]:
b,g={time:(new Date).getTime(),coords:[d.pageX,d.pageY],origin:e(b.target)},l;a.bind("touchmove",c).one("touchend",function(){a.unbind("touchmove",c);g&&l&&l.time-g.time<1E3&&Math.abs(g.coords[0]-l.coords[0])>30&&Math.abs(g.coords[1]-l.coords[1])<75&&g.origin.trigger("swipe").trigger(g.coords[0]>l.coords[0]?"swipeleft":"swiperight");g=l=void 0})}),this.wrapper.bind("swipeleft",function(){b.stop();b.nextSlide()}).bind("swiperight",function(){b.stop();b.prevSlide()}));e(window).bind("resize",function(){b.resize()});
b.resize();b.slides.eq(b.index).css("z-index",2).show();b.options.animated=="kenburns"&&r.canvas&&b.show(this.index,true);b.options.autoplay&&b.start()},resize:function(){this.fx&&(this.slicer&&this.slicer.remove(),this.slides.filter(":animated").stop(true,true),this.next.css({top:0,left:0,"z-index":2}).show(),this.options.animated=="kenburns"&&r.canvas&&(this.element.find("img:animated").stop().css({width:"",height:"",top:"",left:""}).fadeIn("fast"),this.element.find("canvas.tmp").remove()),this.current.css({top:0,
left:0,"z-index":1}).hide());this.fx=false;var a=this.options.width,c=this.options.height;this.slides.css("width","");this.slides.css("height","");this.ul.css("height","");this.wrapper.css("width","");a!="auto"&&this.wrapper.width()<a&&(c=a="auto");this.wrapper.css({width:a=="auto"?this.wrapper.width():a});var a=this.ul.width(),b=c;b=="auto"&&(b=0,this.slides.css("width",a).show().each(function(){b=Math.max(b,e(this).height())}).hide().eq(this.index).show());this.slides.css({height:b,width:this.ul.width()});
this.ul.css("height",b)},nextSlide:function(){this.show(this.slides[this.index+1]?this.index+1:0)},prevSlide:function(){this.show(this.index-1>-1?this.index-1:this.slides.length-1)},show:function(a,c){if(!(this.index==a&&!c||this.fx&&this.options.animated!="kenburns"))this.current=e(this.slides.get(this.index)),this.next=e(this.slides.get(a)),this.animated=this.options.animated,this.duration=this.options.duration,this.easing=this.options.easing,this.dir=a>this.index?"right":"left",this.init=c,this.showCaption(a),
this.element.trigger("slideshow-show",[this.index,a]),this.index=a,this[this.animated]?(this.fx=true,this[this.animated]()):(this.current.hide(),this.next.show())},showCaption:function(a){if(this.caption&&this.captions[a]){var c=e(this.captions.get(a)).html();this.caption.is(":animated")&&this.caption.stop();if(e.trim(c)=="")this.caption.is(":visible")&&this.caption.fadeOut(this.options.caption_animation_duration);else if(this.caption.is(":visible")){var b=this;this.caption.fadeOut(this.options.caption_animation_duration,
function(){e(this).html(c).delay(200).css("opacity","").fadeIn(b.options.caption_animation_duration)})}else this.caption.html(c).fadeIn(this.options.caption_animation_duration)}},start:function(){if(!this.timer){var a=this;this.timer=setInterval(function(){(a.options.animated=="kenburns"||!a.hover&&!a.fx)&&a.nextSlide()},this.options.interval)}},stop:function(){if(this.timer){clearInterval(this.timer);this.tmptimer&&clearTimeout(this.tmptimer);var a=this;this.tmptimer=setTimeout(function(){a.start();
this.tmptimer=false},3E4);this.timer=false}},bindTransitionEnd:function(a){var c=this;e(a).bind("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){c.fx=null;c.next.css({"z-index":"2",left:0,top:0}).show();c.current.hide();c.slicer&&c.slicer.remove()})},randomSimple:function(){var a="top,bottom,fade,slide,scroll,swipe".split(",");this.animated=a[Math.floor(Math.random()*a.length)];this[this.animated]()},randomFx:function(){var a="sliceUp,sliceDown,sliceUpDown,fold,puzzle,boxes,boxesReverse".split(",");
this.animated=a[Math.floor(Math.random()*a.length)];this[this.animated]()},top:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:0,top:this.wrapper.height()*(this.animated=="bottom"?2:-1)}).animate({top:0},{duration:a.duration,easing:a.easing,complete:function(){a.fx=null;a.current.hide()}})},bottom:function(){this.top.apply(this)},left:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:this.current.width()*
(this.animated=="right"?2:-1)}).animate({left:0},{duration:a.duration,easing:this.easing,complete:function(){a.fx=null;a.current.hide()}})},right:function(){this.left()},slide:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:this.current.width()*(this.dir=="right"?2:-1)}).animate({left:0},{duration:a.duration,easing:this.easing,complete:function(){a.fx=null;a.current.hide()}})},fade:function(){var a=this;this.next.css({top:0,left:0,"z-index":1}).fadeIn(a.duration);
this.current.css({"z-index":2}).fadeOut(this.duration,function(){a.fx=null;a.current.hide().css({opacity:1})})},scrollLeft:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:this.current.width()*(this.animated=="scrollRight"?1:-1)}).animate({left:0},{duration:a.duration,easing:this.easing,complete:function(){a.fx=null;a.current.hide()},step:function(c,b){a.current.css("left",(Math.abs(b.start)-Math.abs(c))*(a.animated=="scrollRight"?-1:1))}})},scrollRight:function(){this.scrollLeft(this)},
scroll:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:this.current.width()*(this.dir=="right"?1:-1)}).animate({left:0},{duration:a.duration,easing:this.easing,complete:function(){a.fx=null;a.current.hide()},step:function(c,b){a.current.css("left",(Math.abs(b.start)-Math.abs(c))*(a.dir=="right"?-1:1))}})},swipe:function(){var a=this;this.current.css({"z-index":2});this.next.css({"z-index":1,top:0,left:this.next.width()/3*(a.dir=="right"?1:-1)}).show();
var c=e("<div></div>").css({position:"absolute",top:0,left:0,width:this.current.outerWidth(),height:this.current.outerHeight(),opacity:0,"background-color":"#000"}).appendTo(this.current),b=e("<div></div>").css({position:"absolute",top:0,left:0,width:this.current.outerWidth(),height:this.current.outerHeight(),opacity:0.6,"background-color":"#000"}).appendTo(this.next);c.animate({opacity:0.6},{duration:a.duration});b.animate({opacity:0},{duration:a.duration});this.current.animate({left:(a.dir=="right"?
-1:1)*this.current.width()},{duration:a.duration,easing:"easeOutCubic",complete:function(){a.fx=null;a.current.hide();c.remove();b.remove()}});this.next.animate({left:0},{duration:a.duration,easing:"easeOutCubic"})},slice:function(){var a=this,c=this.next.find("img:first"),b=this.animated=="sliceUp"?"bottom":"top";if(c.length){var d=this.current.find("img:first").position(),f=a.next.width(),j=a.next.height();n(this,d.top,d.left);for(var d=Math.round(this.slicer.width()/this.options.slices),h=0;h<
this.options.slices;h++){var g=h==this.options.slices-1?this.slicer.width()-d*h:d;this.animated=="sliceUpDown"&&(b=(h%2+2)%2==0?"top":"bottom");this.slicer.append(e("<div />").css(b,0).css(m({position:"absolute",left:d*h+"px",width:g+"px",height:0,background:"url("+c.attr("src")+") no-repeat -"+(d+h*d-d)+"px "+b,"background-size":f+"px "+j+"px",opacity:0,transition:"all "+a.duration+"ms ease-in "+h*60+"ms"})))}this.slices=this.slicer.children();this.bindTransitionEnd.apply(this,[this.slices.get(this.slices.length-
1)]);this.current.css({"z-index":1});this.slicer.show();var l=this.wrapper.height();if(r.transition)this.slices.css(m({height:l,opacity:1}));else{var s=0;this.slices.each(function(b){var c=e(this);setTimeout(function(){c.animate({height:l,opacity:1},a.duration,function(){b==a.slices.length-1&&e(this).trigger("transitionend")})},s);s+=60})}}else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null},sliceUp:function(){this.slice.apply(this)},sliceDown:function(){this.slice.apply(this)},
sliceUpDown:function(){this.slice.apply(this)},fold:function(){var a=this,c=this.next.find("img:first");if(c.length){var b=this.current.find("img:first").position(),d=a.next.width(),f=a.next.height();n(this,b.top,b.left);for(var j=Math.round(this.slicer.width()/this.options.slices)+2,b=0;b<this.options.slices+1;b++){var h=b==a.options.slices?a.slicer.width()-j*b:j;this.slicer.append(e("<div />").css(m({position:"absolute",left:j*b+"px",width:h,top:"0px",height:a.options.height,background:"url("+c.attr("src")+
") no-repeat -"+(j+b*j-j)+"px 0%","background-size":d+"px "+f+"px",opacity:0,transform:"scalex(0.0001)",transition:"all "+a.duration+"ms ease-in "+(100+b*60)+"ms"})))}this.slices=this.slicer.children();this.bindTransitionEnd.apply(this,[this.slices.get(this.slices.length-1)]);this.current.css({"z-index":1});this.slicer.show();if(r.transition)this.slices.css(m({opacity:1,transform:"scalex(1)"}));else{var g=0;this.slices.width(0).each(function(b){var c=b==a.options.slices-1?a.slicer.width()-j*b:j,d=
e(this);setTimeout(function(){d.animate({opacity:1,width:c},a.duration,function(){b==a.slices.length-1&&e(this).trigger("transitionend")})},g+100);g+=50})}}else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null},puzzle:function(){var a=this,c=Math.round(this.options.slices/2),b=Math.round(this.wrapper.width()/c),d=Math.round(this.wrapper.height()/b),f=Math.round(this.wrapper.height()/d)+1,j=this.next.find("img:first");if(j.length){var h=this.current.find("img:first").position(),
g=a.next.width(),l=a.next.height();n(this,h.top,h.left);for(var h=this.wrapper.width(),i=0;i<d;i++)for(var k=0;k<c;k++)this.slicer.append(e("<div />").css(m({position:"absolute",left:b*k+"px",width:k==c-1?h-b*k+"px":b+"px",top:f*i+"px",height:f+"px",background:"url("+j.attr("src")+") no-repeat -"+(b+k*b-b)+"px -"+(f+i*f-f)+"px","background-size":g+"px "+l+"px",opacity:0,"-webkit-transform":"translateZ(0)","-moz-transform":"rotate(0)",transition:"all "+a.duration+"ms ease-in 0ms"})));this.slices=t(this.slicer.children());
this.bindTransitionEnd.apply(this,[this.slices.get(this.slices.length-1)]);this.current.css({"z-index":1});this.slicer.show();this.slices.each(function(b){var c=e(this);setTimeout(function(){r.transition?c.css(m({opacity:1})):c.animate({opacity:1},a.duration,function(){b==a.slices.length-1&&e(this).trigger("transitionend")})},100+b*50)})}else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null},boxes:function(){var a=this,c=Math.round(this.options.slices/2),b=Math.round(this.wrapper.width()/
c),d=Math.round(this.wrapper.height()/b),f=Math.round(this.wrapper.height()/d)+1,j=0,h=this.next.find("img:first");if(h.length){var g=this.current.find("img:first").position(),l=a.next.width(),i=a.next.height();n(this,g.top,g.left);for(g=0;g<d;g++)for(var k=0;k<c;k++)this.slicer.append(e("<div />").css(m({position:"absolute",left:b*k+"px",width:0,top:f*g+"px",height:0,background:"url("+h.attr("src")+") no-repeat -"+(b+k*b-b)+"px -"+(f+g*f-f)+"px","background-size":l+"px "+i+"px",opacity:0,transition:"all "+
(100+a.duration)+"ms ease-in 0ms"})).data("base",{width:k==c-1?this.wrapper.width()-b*k:b,height:f}));this.slices=this.slicer.children();this.current.css({"z-index":1});this.slicer.show();var o=0,p=0,q=[];q[o]=[];b=this.animated=="boxesReverse"?this.slices._reverse():this.slices;this.bindTransitionEnd.apply(this,[b.get(b.length-1)]);b.each(function(){q[o][p]=e(this);p++;p==c&&(o++,p=0,q[o]=[])});for(k=f=0;k<c*d;k++){h=k;for(g=0;g<d;g++)h>=0&&h<c&&(function(b,c,d,g){var f=q[b][c];setTimeout(function(){r.transition?
f.css({opacity:"1",width:f.data("base").width,height:f.data("base").height}):f.animate({opacity:"1",width:f.data("base").width,height:f.data("base").height},a.duration,function(){g==a.slices.length-1&&e(this).trigger("transitionend")})},100+d)}(g,h,j,f,b.length),f++),h--;j+=100}}else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null},boxesReverse:function(){this.boxes.apply(this)},kenburns:function(){var a=this,c=this.next.find("img:first"),b=a.options.kenburns_animation_duration||
a.options.interval*2;if(c.length)if(r.canvas){c.stop(false,true).css({width:"",height:""});this.slides.not(this.current).not(this.next).hide();this.current.css({"z-index":1});this.next.css({"z-index":2,visibility:"hidden",opacity:1}).show();this.next.find("canvas.tmp").remove();c.position();var d=c.attr("width"),f=c.attr("height"),j=[{start:["c-l",1],stop:["c-r",1.2]},{start:["t-r",1],stop:["b-l",1.2]},{start:["b-l",1],stop:["t-r",1.2]},{start:["t-c",1],stop:["b-c",1.2]},{start:["c-c",1],stop:["c-c",
1.2]},{start:["b-r",1],stop:["t-l",1.2]},{start:["c-l",1],stop:["c-r",1.2]}],h=j[this.kbi?this.kbi:0],g=e('<canvas class="tmp"></canvas>'),i=function(a,b){var b=b||1,c={top:0,left:0,width:d*b,height:f*b};switch(a){case "t-l":c.top=c.left=0;break;case "t-c":c.top=0;c.left=-1*((c.width-d)/2);break;case "t-r":c.top=0;c.left=-1*(c.width-d);break;case "c-l":c.top=-1*((c.height-f)/2);c.left=0;break;case "c-c":c.top=-1*((c.height-f)/2);c.left=-1*((c.width-d)/2);break;case "c-r":c.top=-1*((c.height-f)/2);
c.left=-1*(c.width-d);break;case "b-l":c.top=-1*(c.height-f);c.left=0;break;case "b-c":c.top=-1*(c.height-f);c.left=-1*((c.width-d)/2);break;case "b-r":c.top=-1*(c.height-f),c.left=-1*(c.width-d)}return c};if(d>this.ul.width()){var m=d/this.ul.width(),d=this.ul.width();f/=m;this.ul.height(f).css("overflow","hidden").css("z-index","4")}g.attr({width:d,height:f}).css({width:d,height:f,opacity:0});c.css({width:"",height:"",top:"",left:""}).after(g).hide();var k=g.get(0).getContext("2d");this.next.css({visibility:"visible"});
g.animate({opacity:1},a.duration);var o=false,p=false,q=false,n=false;c.css(i.apply(this,h.start)).animate(i.apply(this,h.stop),{step:function(a,b){o!==false&&p!==false&&q!==false&&n!==false&&(k.drawImage(c.get(0),o,p,q,n),n=q=p=o=false);b.prop=="width"&&(q=a);b.prop=="height"&&(n=a);b.prop=="left"&&(o=a);b.prop=="top"&&(p=a)},complete:function(){e(this).css({width:"",height:"",top:"",left:""});a.fx=null},easing:"swing",duration:b});a.kbi=j[a.kbi+1]?a.kbi+1:0}else this.fade(this);else this.next.css({"z-index":"2",
left:0,top:0}).show(),this.current.hide(),this.fx=null},scale:function(){var a=this;r.transition?(this.slides.not(this.current).hide(),this.current.one("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){a.fx=null;a.next.css({"z-index":"2",left:0,top:0,opacity:1}).show();e(this).hide().css(m({transition:"none",transform:"none",opacity:1}))}).css(m({"z-index":2,opacity:1,transform:"scale(1)",transition:"all "+a.duration+"ms ease-in-out 0ms"})),this.next.css(m({"z-index":1,
opacity:1,transform:"none"})).show(),a.current.css({"z-index":2}).css(m({opacity:0,transform:"scale(1.5)"}))):this.fade(this)}});e.fn._reverse=[].reverse;var t=function(a){for(var c,b,d=a.length;d;c=parseInt(Math.random()*d),b=a[--d],a[d]=a[c],a[c]=b);return a},n=function(a,c,b){c=c||0;b=b||0;a.slicer=e("<li />").addClass("slices").css({top:c,left:b,position:"absolute",width:a.wrapper.width(),height:a.ul.height(),"z-index":3}).hide().appendTo(a.ul)};e.fn[i.prototype.name]=function(){var a=arguments,
c=a[0]?a[0]:null;return this.each(function(){var b=e(this);if(i.prototype[c]&&b.data(i.prototype.name)&&c!="initialize")b.data(i.prototype.name)[c].apply(b.data(i.prototype.name),Array.prototype.slice.call(a,1));else if(!c||e.isPlainObject(c)){var d=new i;i.prototype.initialize&&d.initialize.apply(d,e.merge([b],a));b.data(i.prototype.name,d)}else e.error("Method "+c+" does not exist on jQuery."+i.name)})}})(jQuery);
